/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

// Hash map to count 
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> m;
        for ( auto c : s )
            m[c]++;
        for ( auto c : t )
        {
            m[c]--;
            if ( m[c] < 0 )
            {
                return c;
            }
        }

        return 'a';
    }
};

// Bit manipulation
class Solution {
public:
    char findTheDifference(string s, string t) {
        char res = 0;
        for ( auto c : s )
            res ^= c;
        for ( auto c : t )
            res ^= c;
        return res;
    }
};